language: rust
sudo: required
dist: trusty

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

script:
  - cargo test -- --test-threads=1

notifications:
  email:
    on-success: never