[package]
name = "olwen"
version = "0.1.0"
authors = ["David Cao <dcao@protonmail.com>"]

[dependencies]
failure = "0.1"
nom = "4.0"
serde = "1.0"
serde_derive = "1.0"
serde_ignored = "0.0.4"
structopt = "0.2"
toml = "0.4"
