[package]
name = "matic"
version = "0.1.0"
authors = ["David Cao <dcao@protonmail.com>"]
license = "MIT"

[dependencies]
failure = "0.1"
nom = "4.0"
semver = { version = "0.9", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_ignored = "0.0.4"
structopt = "0.2"
toml = "0.4"

[lib]
name = "matic"
path = "src/lib/lib.rs"

[[bin]]
name = "matic"
path = "src/bin/main.rs"
